### PR TITLE
GPU hashrate reporting

### PR DESCRIPTION
**Pull request by tomberek**
Allows the setting of a file to use as the source of `hashrate`. Useful hack until ethminer hashrates can be gotten from rpc.

### CODE REVIEW

**Comment by d11e9** [comment]
:-1: PR with hack in title is a Hack

Includes api key, please remove.

**Comment by d11e9** [comment]
cat "999999999999999999999999999999999999" > lib/latest.hash

**Comment by tomberek** [comment]
@d11e9: squashed the commit to remove reference to secret.  Regarding the possibility of incorrect reporting. Well, that's easy enough with a single line change in app.json line 526:
`self.stats.hashrate = 999999999999999999999999999999999999'
So I agree that it's not perfect, but not worse than it is right now. People just want to have a nice report for their own use.

**Comment by cubedro** [comment]
We're working on a fix for this. Ethminer will have eth_submitHashrate so geth will be able to send the correct hashrate through eth_hashrate: https://github.com/ethereum/go-ethereum/pull/1596

**Comment by tomberek** [comment]
Thanks!

**Pull request closed without merging**
